### ISSUE TITLE
Could opflow-java support configuration with .yml format? and dynamic file name?

### ISSUE THREAD

**Issue by hungnguyend** [opflow/opflow-java#1]
Dear opflow-java, I have try this library and it's really strong, simple. Just request new feature could library support .yml file format? and dynamic file name?

Thanks.

**Comment by pnhung177** [comment]
opflow-java has already supported dynamic configuration filename, you can specify the path on OPFLOW_CONFIGURATION environment variable or "opflow.configuration" Java system property. Example:

```shell
OPFLOW_CONFIGURATION=<path-to-your-configfile> java -jar <your-jar-file.jar>
```

or

```shell
java -jar <your-jar-file.jar> -Dopflow.configuration=<path-to-your-configfile>
```

opflow-java will support .yml configuration file soon.

**Comment by hungnguyend** [comment]
Thanks mr @pnhung177
