### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [opflow/opflow-java#4]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/com/devebot/opflow/supports/OpflowKeytool.java: Line number => 54: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR> File name => src/main/java/com/devebot/opflow/supports/OpflowKeytool.java: Line number => 76: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR>

**Comment by pnhung177** [comment]
Hi,

From official docs for KeyStore class:

```
 Typical ways to request a KeyStore object include relying on the default type and providing a specific keystore type.

    To rely on the default type:

        KeyStore ks = KeyStore.getInstance(KeyStore.getDefaultType());
     

    The system will return a keystore implementation for the default type.

    To provide a specific keystore type:

          KeyStore ks = KeyStore.getInstance("JKS");
```

So my codes are ok in lines 54 and 76 in file src/main/java/com/devebot/opflow/supports/OpflowKeytool.java. Please explain more details. Thank you.

**Comment by mhp0rtal** [comment]
Hi,
Thanks for your attention.
No. In fact, those lines say where, which crypto APIs were not used properly.
I reported the cryptographic misuses due to my recent research on how developers employ Java Cryptography Architecture (JCA) APIs in Java applications. I utilized some static analysis tools intended for checking cryptographic practices. The aforementioned misuses in those files were obtained from the results of the tools. The severity of the bug is relative. For instance, Even though MD5 is listed on Java documentation, MD5 is not recommended to use in any language anymore as it is considered insecure. An attacker can try billions of candidate passwords per second on a single GPU. Nevertheless, depending on the scenario the same hash algorithm may not be a problem for file integrity purpose.
There are several instances of cryptographic misuses which could lead to a security vulnerability:
*Do not use ECB mode for encryption.
*Do not use a non-random IV for CBC encryption
*Do not use constant encryption keys.
*Do not use constant salts for PBE.
*Do not use fewer than 1,000 iterations for PBE.
*Do not use static seeds to seed SecureRandom(·)
You can run some static analysis tools on your project (i.e., CryptoLint ) and use the suggestions to make your code more secure.
last but not least, Java documentation advertises some algorithms or all possible parameters for an API but it doesn't mean that they are assumed to be secure.
